### ISSUE TITLE
移动卡是否都支持查阅和修改ICCID

### ISSUE THREAD

**Issue by zhongjianfeipqy** [minghsu/usim_modifier_v3#2]
是否有限制呢？

**Comment by minghsu** [comment]
Hi,

一般正式的商用卡(移動, 聯通等), 只能查閱ICCID
而要修改ICCID, 是須要一組 ADM key, 這組 key 是測試卡廠商會提供的.

PS. 依 'ETSI TS 102 221' 文件的說明, 是無法更改 ICCID 的, 即使你有 ADM key 也一樣是無法更新的.

**Comment by minghsu** [comment]
close this issue due to already answered

**Comment by minghsu** [comment]
close this issue due to already answered
