### ISSUE TITLE
Cannot enter ADM key

### ISSUE THREAD

**Issue by robinleblon** [minghsu/usim_modifier_v3#3]
Firstly, thank you for sharing this tool.
It is by far the simplest and most user friendly open source UICC management tool I have come across...

I have received the ADM code from our USIM supplier, but I am unable to log in with it.
The code I have been provided with an 8-digit decimal number, while the tool is asking for a 16-character hexadecimal code.
Can I use an 8-digit ADM key with this tool?

**Comment by minghsu** [comment]
Hi Robinleblon, 

Thanks for your sharing.
I will modify the ADM check condition by your request soon.

Thansk.

**Comment by minghsu** [comment]
Already add 'admhex' option to configure the adm key format.
