### ISSUE TITLE
Auto adm_verify did not stop when verify fail

### ISSUE THREAD

**Issue by jianiau** [minghsu/usim_modifier_v3#4]
1. Use usim_modifier_v3 and enter correct adm key, usim_modifier_v3  will remember the key.
2. Use other tool change the sim's adm key.
3. Use usim_modifier_v3 read the sim card, it will continue use the remembered adm key until reach max retry.
[20210412-140221.log](https://github.com/minghsu/usim_modifier_v3/files/6294448/20210412-140221.log)

**Comment by minghsu** [comment]
Hi jianiau,

I found the problem due to didn't check the 'return state' from 'adm_verify' state.
I will fix it soon.

Thanks to raise this issue. :)

**Comment by minghsu** [comment]
Hi jianiau,

Already applied the patch, you can pull the last version to verify.

Thanks.

**Comment by jianiau** [comment]
************************************************************************************************************************
*                                                                                                                      *
*                                       USIM 修改員 3.0, ©Copyright 2019 許啊銘                                        *
*                                                                                                                      *
************************************************************************************************************************
讀卡機 'CASTLES EZ100PU 0' 已連接.
ADM 碼不正確, 剩餘 9 次機會, 請重新輸入 (8 ~ 16 位數, 16進制):
