### ISSUE TITLE
Not able to update iccid

### ISSUE THREAD

**Issue by GerardBakker666** [minghsu/usim_modifier_v3#5]
Hi Minghsu,

I am running into the issue that i receive an ERROR when i try to alter the iccid
(Error! Can't update ICCID successfully)
![Schermafdruk van 2022-03-15 15-48-02](https://user-images.githubusercontent.com/101652358/158404311-40513c88-8128-43a8-a89e-646d76f209bf.png)

Any idea how to fix this ?

Thanks in advance...

**Comment by minghsu** [comment]
Hi GerardBakker666,

Sorry for late reply.
Would you please help to provide the last log file from 'logs' folder?

Thanks.

**Comment by GerardBakker666** [comment]
Dont worry ...
I found your response quite fast...
This is the last log file.:
[20220315-154722.log](https://github.com/minghsu/usim_modifier_v3/files/8263598/20220315-154722.log)
e

**Comment by minghsu** [comment]
Hi GerardBakker666,

I saw the ADM key already verified, but still got the security fail when you update EF_ICCID field.
From the FCP response of EF_ICCID, the access condition is defined in "EF_ARR" field.
I need a few days to implement "arr" plugin to dump EF_ARR records.

Then ... try to study the chapter of "security features" from TS-102-221 spec.  ^^||

Thanks.

## verify ADM success
03-15 15:47:22 adm_verify       DEBUG    ENTER
03-15 15:47:22 uicc             DEBUG    TX> 00 20 00 0A 08 39 32 32 35 32 32 38 34
03-15 15:47:22 uicc             DEBUG    RX< , 90 00
03-15 15:47:22 adm_verify       DEBUG    EXIT


## set iccid
03-15 15:47:46 execute          INFO     iccid set=99020496
03-15 15:47:46 iccid            DEBUG    ENTER
## access condition should defined in record 7 of EF_ARR(2F06)
03-15 15:47:46 uicc             DEBUG    RX< 62 1E 82 02 41 21 83 02 2F E2 A5 06 80 01 71 92 01 00 8A 01 05 8B 03 2F 06 07 80 02 00 0A 88 00, 90 00
## update iccid
03-15 15:47:46 uicc             DEBUG    TX> 00 D6 00 00 0B 99 20 40 69 04 00 00 73 80 10 05
## 6982 - Security status not satisfied
03-15 15:47:46 uicc             DEBUG    RX< , 69 82

**Comment by GerardBakker666** [comment]
Hi Minghsu,

No worry's ...
Take your time...
Hope you get this solved.. :-)

Op do 17 mrt. 2022 om 13:52 schreef Hsu Chih-Ming ***@***.***

**Comment by minghsu** [comment]
Hi GerardBakker666,

Please update the last 'usim_modifier_v3', and execute 'arr' plugin, then provide the log file again.

Thanks :)

**Comment by GerardBakker666** [comment]
Here you go..
[20220319-135908.log](https://github.com/minghsu/usim_modifier_v3/files/8309270/20220319-135908.log)

**Comment by minghsu** [comment]
Hi GerardBakker666,

This USIM card is not allow to update the EF_ICCID field.
According the EF_ARR record, we can list all the access conditions in the below:

- 80 01 01 90 00 (Read): Always
- 80 01 02 97 00 (Update): The '97' mean 'NEVER' 
- 80 01 18 A4 06 83 01 0A 95 01 08 (activate/deactivate): ADM1

So, it's not an issue.
If you need to update the ICCID, please bought the test USIM.

Thanks.

---
03-19 14:01:09 uicc             DEBUG    TX> 00 B2 07 04 32
03-19 14:01:09 uicc             DEBUG    RX< 80 01 01 90 00 80 01 02 97 00 80 01 18 A4 06 83 01 0A 95 01 08 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF, 90 00

**Comment by GerardBakker666** [comment]
> Hi GerardBakker666,
> 
> This USIM card is not allow to update the EF_ICCID field. According the EF_ARR record, we can list all the access conditions in the below:
> 
>     * 80 01 01 90 00 (Read): Always
> 
>     * 80 01 02 97 00 (Update): The '97' mean 'NEVER'
> 
>     * 80 01 18 A4 06 83 01 0A 95 01 08 (activate/deactivate): ADM1
> 
> 
> So, it's not an issue. If you need to update the ICCID, please bought the test USIM.
> 
> Thanks.
> 
> 03-19 14:01:09 uicc DEBUG TX> 00 B2 07 04 32 03-19 14:01:09 uicc DEBUG RX< 80 01 01 90 00 80 01 02 97 00 80 01 18 A4 06 83 01 0A 95 01 08 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF, 90 00

OK...
Good to know...
I have learned something new today ...!!!
thanks for your support...(Love your tool by the way...!!!)
